# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'Default'  

variables:
  buildConfiguration: 'Release'
  solution: '**/PetShopService.sln'
  project: '**/PetShopService.csproj'
  tests: '**/PetShopServiceTest.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'

- task: NuGetCommand@2
  name: 'RestoreNuget'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'UnitTest'
  inputs:
    command: 'test'
    projects: '$(tests)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: True
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'publishArtifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'petshopserviceartifact'
    publishLocation: 'Container'